<script lang="ts">
  import { onMount } from 'svelte';
  import { getSupabaseContext } from '$lib/data/supabase/context';
  import { fetchUserRole } from '$lib/data/supabase/role';
  import GeorefSyncPanel from '$lib/features/admin/GeorefSyncPanel.svelte';
  import '$styles/pages/admin-bulk.css';

  // ── session / role guard ────────────────────────────────────────────────
  const { supabase, session } = getSupabaseContext();
  let role: 'user' | 'mod' | 'admin' = 'user';
  let roleChecked = false;

  async function checkRole() {
    if (!session?.user?.id) {
      role = 'user';
      roleChecked = true;
      return;
    }
    role = (await fetchUserRole(supabase, session.user.id)) ?? 'user';
    roleChecked = true;
  }
  onMount(checkRole);

  // ── grid state ──────────────────────────────────────────────────────────
  type Row = {
    path: string; // local filesystem path on the admin's machine
    name: string;
    year: string;
    collection: string;
    map_type: string;
    location: string;
    // computed after create
    id?: string;
    status?: 'pending' | 'created' | 'failed';
    error?: string;
  };

  const blankRow = (): Row => ({
    path: '',
    name: '',
    year: '',
    collection: defaultCollection,
    map_type: 'topographic',
    location: '',
  });

  let defaultCollection = "Service Géographique de l'Indochine";
  let rows: Row[] = [blankRow()];
  let creating = false;
  let resultScript = '';
  let createSummary = '';

  function addRow() {
    rows = [...rows, blankRow()];
  }
  function removeRow(i: number) {
    rows = rows.filter((_, j) => j !== i);
    if (rows.length === 0) addRow();
  }
  function clearAll() {
    rows = [blankRow()];
    resultScript = '';
    createSummary = '';
  }

  // ── Paste parser: accepts tab-separated, CSV, or simple "path" lists ───
  // Tries to be forgiving. If the line has tabs, splits on tab. If it has
  // commas and looks like CSV, splits on comma. Otherwise treats whole line
  // as path and tries to auto-parse name/year from the filename.
  function parsePaste(text: string) {
    const lines = text
      .split(/\r?\n/)
      .map((l) => l.trim())
      .filter(Boolean);
    const parsed: Row[] = [];
    for (const line of lines) {
      let cells: string[];
      if (line.includes('\t')) cells = line.split('\t');
      else if (line.split(',').length >= 3) cells = line.split(',');
      else cells = [line];

      const [path = '', name0 = '', year0 = '', collection0 = '', map_type0 = '', location0 = ''] =
        cells.map((s) => s.trim());
      const auto = autoFromFilename(path);
      parsed.push({
        path,
        name: name0 || auto.name,
        year: year0 || auto.year,
        collection: collection0 || defaultCollection,
        map_type: map_type0 || 'topographic',
        location: location0,
      });
    }
    if (parsed.length) rows = parsed;
  }

  function autoFromFilename(path: string): { name: string; year: string } {
    if (!path) return { name: '', year: '' };
    const base =
      path
        .split('/')
        .pop()
        ?.replace(/\.[^.]+$/, '') ?? '';
    const yearMatch = base.match(/(\d{4})\s*$/);
    const year = yearMatch ? yearMatch[1] : '';
    let name = year ? base.slice(0, yearMatch!.index).trim() : base;
    // Drop leading "<sheet#> " prefix (e.g. "20 Ha Noi" → "Ha Noi")
    name = name.replace(/^\d+[a-z]?\.?\s+/, '').trim();
    return { name, year };
  }

  function applyAutoName(i: number) {
    const auto = autoFromFilename(rows[i].path);
    rows[i] = { ...rows[i], name: auto.name || rows[i].name, year: auto.year || rows[i].year };
    rows = rows;
  }

  // ── Create batch ─────────────────────────────────────────────────────────
  async function createBatch() {
    creating = true;
    createSummary = '';
    let okCount = 0,
      failCount = 0;
    const cmds: string[] = [
      '#!/usr/bin/env bash',
      '# Generated by /admin?tab=bulk — run from the repo root.',
      'set -euo pipefail',
      'cd "$(dirname "$0")"',
      '',
    ];

    for (let i = 0; i < rows.length; i++) {
      const r = rows[i];
      if (!r.path.trim() || !r.name.trim()) {
        rows[i] = { ...r, status: 'failed', error: 'path and name required' };
        failCount++;
        continue;
      }
      try {
        const payload: any = {
          name: r.name.trim(),
          year: r.year ? Number(r.year) : null,
          collection: r.collection.trim() || null,
          map_type: r.map_type.trim() || null,
          location: r.location.trim() || null,
          source_type: 'self',
          status: 'draft',
        };
        const res = await fetch('/api/admin/maps', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
        if (!res.ok) {
          const err = await res.json().catch(() => ({ message: res.statusText }));
          throw new Error(err.message || `HTTP ${res.status}`);
        }
        const created = await res.json();
        rows[i] = { ...r, id: created.id, status: 'created', error: undefined };
        cmds.push(`./scripts/tile_map.sh ${created.id} ${shellQuote(r.path)}`);
        cmds.push(`# ↑ ${r.name} (${r.year || '?'})`);
        okCount++;
      } catch (e: any) {
        rows[i] = { ...r, status: 'failed', error: e.message };
        failCount++;
      }
    }
    rows = rows;

    cmds.push('');
    cmds.push('echo "✓ All tiling jobs done."');
    resultScript = cmds.join('\n');
    createSummary = `${okCount} created · ${failCount} failed`;
    creating = false;
  }

  function shellQuote(s: string): string {
    return `'${s.replace(/'/g, "'\\''")}'`;
  }

  async function copyScript() {
    if (!resultScript) return;
    try {
      await navigator.clipboard.writeText(resultScript);
    } catch {}
  }

  // ── Bulk metadata refresh (set thumb + clean name) for created rows ────
  async function backfillCreated() {
    const created = rows.filter((r) => r.id);
    for (const r of created) {
      try {
        const info = await fetch(`https://iiif.maparchive.vn/iiif/${r.id}/info.json`).then((x) =>
          x.ok ? x.json() : null
        );
        if (!info?.sizes?.length) continue;
        const last = info.sizes[info.sizes.length - 1];
        const thumb = `https://iiif.maparchive.vn/iiif/${r.id}/full/${last.width},${last.height}/0/default.jpg`;
        await fetch(`/api/admin/maps/${r.id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            thumbnail: thumb,
            iiif_image: `https://iiif.maparchive.vn/iiif/${r.id}`,
          }),
        });
      } catch {}
    }
    createSummary += ' · thumbnails backfilled';
  }
</script>

<svelte:head><title>Bulk Upload — Admin</title></svelte:head>

<div class="admin-bulk-page">
  <header class="bulk-head">
    <a class="back-link" href="/catalog">← Catalog</a>
    <h2 class="section-title-sm">Bulk Map Upload</h2>
    <p class="section-desc">
      Insert many maps at once. Tiling still runs locally — this page gives you the script.
    </p>
  </header>

  {#if !roleChecked}
    <p class="empty-state is-block">Checking access…</p>
  {:else if role !== 'admin'}
    <p class="empty-state is-block error">Admin only.</p>
  {:else}
    <section class="section-card">
      <h3 class="section-title-sm">1. Defaults</h3>
      <label class="field">
        <span>Default collection</span>
        <input
          type="text"
          bind:value={defaultCollection}
          placeholder="e.g. Service Géographique de l'Indochine"
        />
      </label>
    </section>

    <section class="section-card">
      <h3 class="section-title-sm">2. Maps</h3>
      <p class="hint">
        Paste from a spreadsheet (one row per line, tab- or comma-separated: path, name, year,
        collection, map_type, location) — or just paste a list of paths and we'll auto-parse
        name/year from the filename.
      </p>
      <textarea
        rows="3"
        placeholder="/Users/you/maps/20 Ha Noi 1903.jpg&#10;/Users/you/maps/31 Hai Phong 1904.jpg"
        on:paste|preventDefault={(e) => {
          const t = e.clipboardData?.getData('text') ?? '';
          parsePaste(t);
        }}></textarea>

      <div class="grid-wrap">
        <table class="grid data-table">
          <thead>
            <tr>
              <th>Local path</th>
              <th>Name</th>
              <th>Year</th>
              <th>Collection</th>
              <th>Map type</th>
              <th>Location</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {#each rows as row, i (i)}
              <tr class:row-ok={row.status === 'created'} class:row-bad={row.status === 'failed'}>
                <td
                  ><input
                    type="text"
                    bind:value={row.path}
                    on:blur={() => applyAutoName(i)}
                    placeholder="/abs/path/to/file.jpg"
                  /></td
                >
                <td><input type="text" bind:value={row.name} /></td>
                <td><input type="text" bind:value={row.year} /></td>
                <td><input type="text" bind:value={row.collection} /></td>
                <td><input type="text" bind:value={row.map_type} /></td>
                <td><input type="text" bind:value={row.location} /></td>
                <td class="status-cell">
                  {#if row.status === 'created'}<span class="ok" title={row.id}>✓</span>
                  {:else if row.status === 'failed'}<span class="bad" title={row.error}>✗</span>
                  {:else}—{/if}
                </td>
                <td
                  ><button
                    class="btn is-xs is-ghost"
                    on:click={() => removeRow(i)}
                    aria-label="Remove row">✕</button
                  ></td
                >
              </tr>
            {/each}
          </tbody>
        </table>
      </div>

      <div class="row-actions">
        <button class="btn" on:click={addRow}>+ Add row</button>
        <button class="btn" on:click={clearAll}>Clear all</button>
        <span class="grow"></span>
        <button class="btn is-lg is-primary" on:click={createBatch} disabled={creating}>
          {creating ? 'Creating…' : `Create ${rows.length} map row${rows.length === 1 ? '' : 's'}`}
        </button>
      </div>
      {#if createSummary}<p class="empty-state">{createSummary}</p>{/if}
    </section>

    <GeorefSyncPanel />

    {#if resultScript}
      <section class="section-card">
        <h3 class="section-title-sm">3. Run this locally to tile + upload</h3>
        <p class="hint">
          Save as <code>tile_batch.sh</code> in your repo root,
          <code>chmod +x</code>, then run. After tiling, click the backfill button below to set IIIF
          URLs and thumbnails on the new map rows.
        </p>
        <div class="script-actions">
          <button class="btn" on:click={copyScript}>Copy script</button>
          <button class="btn" on:click={backfillCreated}>Backfill thumbnails (after tiling)</button>
        </div>
        <pre class="script">{resultScript}</pre>
      </section>
    {/if}
  {/if}
</div>
