# -*- coding: utf-8 -*-
"""vma_mapsam2_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFnF0Kzc0NHpubtCbwSZlNve3tkvF6JW

<a href="https://colab.research.google.com/github/lqtue/vietnam-map-archive/blob/main/vma_mapsam2_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VMA × MapSAM2 — Fine-tune SAM2 on Historical Map Footprints

This notebook:
1. Fetches volunteer-traced building footprints **directly from Supabase** (no local server needed)
2. Constructs IIIF crop URLs via Allmaps annotation data
3. Converts footprints to MapSAM2's image + binary mask directory format
4. Fine-tunes SAM2 with LoRA on the dataset
5. Evaluates and visualises results

**Runtime**: GPU (T4 or better). Runtime → Change runtime type → GPU.

## 0. GPU check + base installs
"""

!nvidia-smi

import subprocess, sys

# Core deps
!pip install -q pillow requests tqdm matplotlib supabase

# SAM2 base (MapSAM2 bundles its own copy but pip-installing ensures Hydra/iopath are present)
!pip install -q 'git+https://github.com/facebookresearch/segment-anything-2.git' 2>/dev/null || true

print('✓ Base installs done')

"""## 1. Config — set these before running"""

import os
os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

# ── Supabase (public read-only) ───────────────────────────────────────────────
SUPABASE_URL      = 'https://trioykjhhwrruwjsklfo.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaW95a2poaHdycnV3anNrbGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0OTQwNzMsImV4cCI6MjA4NjA3MDA3M30.iGYrRXPlkHmeBhJa4T41tOteyTBtJ5x-B2_96Dpg3cE'

# ── Category Config ──────────────────────────────────────────────────────────
CATEGORY_FILTER = 'building' # Change this to 'land_plot' as needed
CATEGORY_IDS = {'building': 1, 'land_plot': 2}

# ── Training data & IIIF ──────────────────────────────────────────────────────
MAP_ID = '3d065384-bb09-4b8c-b46b-bf006d0c3ba3'
STATUS = 'submitted'
PAD, SIZE = 64, 1024

# ── Model Params ──────────────────────────────────────────────────────────────
CKPT_NAME, ENCODER, SAM_CONFIG = 'sam2_hiera_small', 'vit_s', 'sam2_hiera_s'
LR, LORA_RANK, BATCH_SIZE = 1e-4, 4, 2

# ── Paths ─────────────────────────────────────────────────────────────────────
MAPSAM2_DIR  = '/content/MapSAM2'
DATA_DIR     = '/content/vma_dataset'
CKPT_PATH    = f'{MAPSAM2_DIR}/checkpoints/{CKPT_NAME}.pt'

# ── Drive Sync ────────────────────────────────────────────────────────────────
USE_DRIVE   = True
# Consistent naming for Drive cache
DRIVE_CACHE = f'/content/drive/MyDrive/vma_mapsam2_{CATEGORY_FILTER}_cache'

print(f'Configured for: {CATEGORY_FILTER}')
print(f'Drive folder: {DRIVE_CACHE}')

"""## 2. (Optional) Mount Google Drive to cache downloads"""

import os
from google.colab import drive

# Mount drive if not already mounted
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# Create the main cache folder and subfolders
folders = [
    DRIVE_CACHE,
    os.path.join(DRIVE_CACHE, 'images'),
    os.path.join(DRIVE_CACHE, 'masks'),
    os.path.join(DRIVE_CACHE, 'models')
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f'Ready: {folder}')

# Update config to ensure USE_DRIVE is True for subsequent cells
USE_DRIVE = True
print('\n✓ Drive cache structure initialized and USE_DRIVE set to True.')

"""## 3. Clone MapSAM2 + download SAM2 checkpoint"""

import os

if not os.path.exists(MAPSAM2_DIR):
    !git clone https://github.com/Xue-Xia/MapSAM2 {MAPSAM2_DIR}
else:
    print('MapSAM2 already cloned')

os.chdir(MAPSAM2_DIR)
!pip install -q -e . 2>/dev/null

# Download checkpoint if not already present
os.makedirs(f'{MAPSAM2_DIR}/checkpoints', exist_ok=True)
if not os.path.exists(CKPT_PATH):
    CKPT_URLS = {
        'sam2_hiera_tiny':      'https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt',
        'sam2_hiera_small':     'https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_small.pt',
        'sam2_hiera_base_plus': 'https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_base_plus.pt',
        'sam2_hiera_large':     'https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt',
    }
    url = CKPT_URLS[CKPT_NAME]
    print(f'Downloading {CKPT_NAME}...')
    !wget -q --show-progress -O {CKPT_PATH} {url}
else:
    print(f'Checkpoint already at {CKPT_PATH}')

print('✓ MapSAM2 ready')

"""## 4. Fetch VMA footprint data directly from Supabase

This cell replicates the logic from the VMA `/api/export/footprints?format=coco` endpoint
but runs entirely in Colab — no local server or ngrok needed.
"""

import requests, json, math
from collections import Counter

HEADERS = {
    'apikey': SUPABASE_ANON_KEY,
    'Authorization': f'Bearer {SUPABASE_ANON_KEY}',
    'Content-Type': 'application/json',
}

print(f'Querying Supabase for map_id={MAP_ID}, status={STATUS}...')

resp = requests.get(
    f'{SUPABASE_URL}/rest/v1/footprint_submissions',
    headers=HEADERS,
    params={
        'select': '*,label_tasks(map_id,allmaps_id,maps(allmaps_id))',
        'status': f'eq.{STATUS}',
        'map_id': f'eq.{MAP_ID}',
    },
    timeout=30,
)
resp.raise_for_status()
rows = resp.json()

annotation_cache = {}

def get_iiif_base(allmaps_id):
    if allmaps_id in annotation_cache: return annotation_cache[allmaps_id]
    try:
        r = requests.get(f'https://annotations.allmaps.org/images/{allmaps_id}', timeout=15)
        if not r.ok: return None
        base = r.json().get('items', [{}])[0].get('target', {}).get('source', {}).get('id')
        annotation_cache[allmaps_id] = base
        return base
    except: return None

# Standardized IIIF parameters: {region}/{size}/{rotation}/{quality}.{format}
ROTATION = '0'
QUALITY = 'default'
FORMAT = 'jpg'

coco_images = []
coco_annotations = []
ann_id = 1

for row in rows:
    if row.get('feature_type') != CATEGORY_FILTER:
        continue

    task = row.get('label_tasks') or {}
    maps_join = task.get('maps') or {}
    allmaps_id = row.get('allmaps_id') or task.get('allmaps_id') or maps_join.get('allmaps_id')
    if not allmaps_id: continue

    iiif_base = get_iiif_base(allmaps_id)
    if not iiif_base: continue

    pixel_ring = row.get('pixel_polygon')
    if not pixel_ring: continue

    xs, ys = [pt[0] for pt in pixel_ring], [pt[1] for pt in pixel_ring]
    x_min, y_min, x_max, y_max = min(xs), min(ys), max(xs), max(ys)
    crop_x, crop_y = max(0, round(x_min - PAD)), max(0, round(y_min - PAD))
    crop_w, crop_h = round(x_max - x_min + 2 * PAD), round(y_max - y_min + 2 * PAD)

    # Strictly following: {identifier}/{region}/{size}/{rotation}/{quality}.{format}
    region = f'{crop_x},{crop_y},{crop_w},{crop_h}'
    size = f'{SIZE},'
    iiif_url = f'{iiif_base}/{region}/{size}/{ROTATION}/{QUALITY}.{FORMAT}'

    scale = SIZE / crop_w
    rel_seg = []
    for x, y in pixel_ring:
        rel_seg.extend([round((x - crop_x) * scale), round((y - crop_y) * scale)])

    coco_images.append({'id': ann_id, 'footprint_id': row['id'], 'iiif_url': iiif_url, 'width': SIZE, 'height': round((crop_h / crop_w) * SIZE)})
    coco_annotations.append({'id': ann_id, 'image_id': ann_id, 'category_id': CATEGORY_IDS.get(CATEGORY_FILTER, 1), 'segmentation': [rel_seg], 'bbox': [round((x_min-crop_x)*scale), round((y_min-crop_y)*scale), round((x_max-x_min)*scale), round((y_max-y_min)*scale)], 'area': (x_max-x_min)*(y_max-y_min)*scale*scale, 'iscrowd': 0})
    ann_id += 1

coco = {'info': {'description': f'VMA {CATEGORY_FILTER}'}, 'categories': [{'id': CATEGORY_IDS.get(CATEGORY_FILTER, 1), 'name': CATEGORY_FILTER}], 'images': coco_images, 'annotations': coco_annotations}
print(f'Prepared {len(coco_images)} samples for {CATEGORY_FILTER}')

"""## 5. Convert to MapSAM2 format

Downloads each IIIF crop image and renders the polygon annotation as a binary mask.
Images cached to Drive if `USE_DRIVE=True`.
"""

import random, pathlib, time, requests, json
from PIL import Image, ImageDraw
from io import BytesIO
from tqdm import tqdm
import shutil

print(f"Checking dataset at {DATA_DIR} (Incremental Mode + Retries)")

random.seed(42)
anns_by_img = {a['image_id']: a for a in coco['annotations']}
images = list(coco['images'])
random.shuffle(images)
n_train = int(len(images) * TRAIN_SPLIT)
splits  = {'train': images[:n_train], 'val': images[n_train:]}

root = pathlib.Path(DATA_DIR)
for mode in ('train', 'val'):
    (root / mode).mkdir(parents=True, exist_ok=True)
    (root / 'annotation' / mode).mkdir(parents=True, exist_ok=True)

(root / 'coco.json').write_text(json.dumps(coco, indent=2))

skipped = 0
saved   = {'train': 0, 'val': 0}
MAX_RETRIES = 3
TIMEOUT = 120

for mode, items in splits.items():
    for item in tqdm(items, desc=f'Preparing {mode}'):
        stem = item['footprint_id']
        img_path  = root / mode / f'{stem}.png'
        mask_path = root / 'annotation' / mode / f'{stem}.png'

        if img_path.exists() and mask_path.exists():
            saved[mode] += 1
            continue

        success = False
        for attempt in range(MAX_RETRIES):
            try:
                r = requests.get(item['iiif_url'], timeout=TIMEOUT)
                r.raise_for_status()
                pil_img = Image.open(BytesIO(r.content)).convert('RGB')

                # Render binary mask
                ann = anns_by_img.get(item['id'])
                if not ann: raise ValueError("No annotation found")

                seg = ann['segmentation'][0]
                pts = list(zip(seg[::2], seg[1::2]))
                mask = Image.new('L', (item['width'], item['height']), 0)
                ImageDraw.Draw(mask).polygon(pts, fill=255)

                # Save both
                pil_img.save(img_path)
                mask.save(mask_path)
                saved[mode] += 1
                success = True
                break

            except Exception as e:
                if attempt < MAX_RETRIES - 1:
                    time.sleep(2) # Wait before retry
                continue

        if not success:
            skipped += 1

print(f'\n✓ Dataset Status: {saved["train"]} train, {saved["val"]} val total on disk. ({skipped} failed after retries)')

"""## 5b. Spot-check: preview a sample image + mask"""

import matplotlib.pyplot as plt
import numpy as np

sample_imgs = sorted((root / 'train').glob('*.png'))[:4]
fig, axes = plt.subplots(len(sample_imgs), 2, figsize=(10, 4 * len(sample_imgs)))
if len(sample_imgs) == 1:
    axes = [axes]

for ax_row, img_path in zip(axes, sample_imgs):
    stem = img_path.stem
    mask_path = root / 'annotation' / 'train' / f'{stem}.png'

    img  = np.array(Image.open(img_path))
    mask = np.array(Image.open(mask_path))

    ax_row[0].imshow(img)
    ax_row[0].set_title(f'Image: {stem[:16]}...')
    ax_row[0].axis('off')

    # Overlay mask as semi-transparent red
    ax_row[1].imshow(img)
    overlay = np.zeros((*mask.shape, 4), dtype=np.uint8)
    overlay[mask > 127] = [255, 50, 50, 140]
    ax_row[1].imshow(overlay)
    ax_row[1].set_title(f'GT Mask (white pixels: {(mask>127).sum()})')
    ax_row[1].axis('off')

plt.tight_layout()
plt.show()

"""## 6. Train"""

import os
os.chdir(MAPSAM2_DIR)

!pip install -q tensorboardX

CMD = (
    f'python train_2d.py'
    f' -net sam2'
    f' -encoder {ENCODER}'
    f' -sam_ckpt {CKPT_PATH}'
    f' -sam_config {SAM_CONFIG}'
    f' -data_path {DATA_DIR}'
    f' -image_size 1024'
    f' -out_size 1024'
    f' -b {BATCH_SIZE}'
    f' -lr {LR}'
    f' -rank {LORA_RANK}'
    f' -exp_name vma_landplots'
    f' -val_freq 1'
    f' 2>&1 | tee /content/train.log'
)
print(CMD)
!{CMD}

"""## 7. Parse training metrics"""

import re, matplotlib.pyplot as plt

log = open('/content/train.log').read()

# 1. Parse metrics using updated regex that matches your exact log format
train_losses = [float(x) for x in re.findall(r'INFO:root:Train loss:\s*([\d.]+)', log)]
val_data = re.findall(r'INFO:root:Total loss:\s*([\d.]+),\s*IOU:\s*([\d.]+),\s*DICE:\s*([\d.]+)', log)

val_losses = [float(x[0]) for x in val_data]
iou_vals   = [float(x[1]) for x in val_data]
dice_vals  = [float(x[2]) for x in val_data]

if dice_vals:
    best_epoch = dice_vals.index(max(dice_vals))
    print(f'Best Dice : {max(dice_vals):.4f}  (epoch {best_epoch})')

if iou_vals:
    best_epoch_iou = iou_vals.index(max(iou_vals))
    print(f'Best IOU  : {max(iou_vals):.4f}  (epoch {best_epoch_iou})')

# 2. Plot the charts
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

if train_losses or val_losses:
    if train_losses: axes[0].plot(train_losses, marker='o', label='Train Loss')
    if val_losses: axes[0].plot(val_losses, marker='s', label='Val (Total) Loss')
    axes[0].set_title('Loss Curve')
    axes[0].set_xlabel('Epoch')
    axes[0].legend()

if dice_vals or iou_vals:
    if dice_vals: axes[1].plot(dice_vals, marker='o', label='Dice')
    if iou_vals: axes[1].plot(iou_vals, marker='s', label='IoU')
    axes[1].set_title('Validation Metrics')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylim(0, 1)
    axes[1].legend()

plt.tight_layout()
plt.show()

# 3. Fallback warning if it's still empty
if not dice_vals:
    print('\nCould not parse metrics. Training might not have generated full epochs yet.')

"""## 8. Visual inference on validation set"""

import torch, glob, os, sys, shutil
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import pathlib

# Re-define necessary config variables for this cell's scope
MAPSAM2_DIR  = '/content/MapSAM2'
DATA_DIR     = '/content/vma_dataset'
CKPT_NAME    = 'sam2_hiera_small'
ENCODER      = 'vit_s'
SAM_CONFIG   = 'sam2_hiera_s'
LORA_RANK    = 4
CKPT_PATH    = f'{MAPSAM2_DIR}/checkpoints/{CKPT_NAME}.pt'

os.chdir(MAPSAM2_DIR)
sys.path.insert(0, MAPSAM2_DIR)

# 1. Prepare test directories
root = pathlib.Path(DATA_DIR)
test_img_dir = root / 'test'
test_ann_dir = root / 'annotation' / 'test'

if not test_img_dir.exists():
    shutil.copytree(root / 'val', test_img_dir)
if not test_ann_dir.exists():
    shutil.copytree(root / 'annotation' / 'val', test_ann_dir)

# 2. Find best checkpoint - using the identified path
# Sort by modification time to get the latest created log folder first
latest_log_dir = None
log_dirs = sorted(glob.glob(f'{MAPSAM2_DIR}/logs/vma_landplots*'), key=os.path.getmtime)
if log_dirs:
    latest_log_dir = log_dirs[-1]

if latest_log_dir:
    ckpts = sorted(glob.glob(f'{latest_log_dir}/Model/*.pth'))

    if not ckpts:
        print('No checkpoint found in the latest log directory. Please check the path manually.')
        best_ckpt = None # Ensure best_ckpt is None if no checkpoint is found
    else:
        # Use the latest epoch checkpoint from the latest run
        best_ckpt = ckpts[-1]
        print(f'Using latest checkpoint from the latest run: {best_ckpt}')
else:
    print('No training log directory found.')
    best_ckpt = None

if best_ckpt:
    # 3. Run test-mode inference
    CMD_TEST = (
        f'python train_2d.py'
        f' -net sam2 -encoder {ENCODER}'
        f' -sam_ckpt {CKPT_PATH}'
        f' -sam_config {SAM_CONFIG}'
        f' -data_path {DATA_DIR}'
        f' -test_path {DATA_DIR}'
        f' -image_size 1024 -out_size 1024'
        f' -b 1 -rank {LORA_RANK}'
        f' -ft_ckpt {best_ckpt}'
        f' -test'
        f' 2>&1 | tee /content/test.log'
    )
    !{CMD_TEST}

    # 4. Visualise GT vs predicted masks
    val_imgs = sorted((root / 'test').glob('*.png'))[:4]

    # Find the most recently created 'Pred' folder from this specific test run
    all_pred_dirs = sorted(glob.glob(f'{MAPSAM2_DIR}/logs/*/Pred'), key=os.path.getmtime)
    if all_pred_dirs:
        pred_dir = pathlib.Path(all_pred_dirs[-1])
        print(f"Reading predictions from: {pred_dir}")
    else:
        pred_dir = pathlib.Path('missing')

    fig, axes = plt.subplots(len(val_imgs), 3, figsize=(15, 5 * len(val_imgs)))
    if len(val_imgs) == 1: axes = [axes]

    for ax_row, img_path in zip(axes, val_imgs):
        stem = img_path.stem
        mask_path = root / 'annotation' / 'test' / f'{stem}.png'

        img  = np.array(Image.open(img_path))
        gt   = np.array(Image.open(mask_path)) > 127

        ax_row[0].imshow(img); ax_row[0].set_title('Image'); ax_row[0].axis('off')

        gt_overlay = np.zeros((*gt.shape, 4), dtype=np.uint8)
        gt_overlay[gt] = [0, 200, 100, 160]
        ax_row[1].imshow(img); ax_row[1].imshow(gt_overlay)
        ax_row[1].set_title('Ground Truth'); ax_row[1].axis('off')

        pred_candidates = list(pred_dir.glob(f'*{stem}*.*'))
        if pred_candidates:
            pred_img = Image.open(pred_candidates[0]).convert('L').resize((gt.shape[1], gt.shape[0]), Image.NEAREST)
            pred = np.array(pred_img) > 127
            pred_overlay = np.zeros((*pred.shape, 4), dtype=np.uint8)
            pred_overlay[pred] = [255, 100, 0, 160]
            ax_row[2].imshow(img); ax_row[2].imshow(pred_overlay)
            intersection = (gt & pred).sum()
            union = (gt | pred).sum()
            iou = intersection / max(union, 1)
            ax_row[2].set_title(f'Prediction IoU={iou:.3f}')
        else:
            ax_row[2].imshow(img); ax_row[2].set_title('Prediction not found')
        ax_row[2].axis('off')

    plt.tight_layout()
    plt.show()
else:
    print('Skipping inference as no valid checkpoint was found.')

"""## 9. Save trained model to Drive

Copy the best checkpoint and the full COCO dataset metadata to Drive for later use.
"""

import shutil, pathlib, pandas as pd, datetime

if USE_DRIVE and 'best_ckpt' in dir() and best_ckpt:
    # 1. Setup paths
    out_dir = pathlib.Path(DRIVE_CACHE)
    model_dir = out_dir / 'models'
    report_path = out_dir / 'performance_report.csv'
    model_dir.mkdir(parents=True, exist_ok=True)

    # 2. Extract metrics from current run
    # Using max values from the training session parsed in Step 7
    current_dice = max(dice_vals) if 'dice_vals' in locals() and dice_vals else 0.0
    current_iou = max(iou_vals) if 'iou_vals' in locals() and iou_vals else 0.0

    # 3. Update Performance Report
    new_entry = {
        'timestamp': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'category': CATEGORY_FILTER,
        'best_dice': current_dice,
        'best_iou': current_iou,
        'ckpt_name': pathlib.Path(best_ckpt).name,
        'run_dir': latest_log_dir
    }

    if report_path.exists():
        df_report = pd.read_csv(report_path)
        df_report = pd.concat([df_report, pd.DataFrame([new_entry])], ignore_index=True)
    else:
        df_report = pd.DataFrame([new_entry])

    df_report.to_csv(report_path, index=False)
    print(f'✓ Performance report updated at {report_path}')

    # 4. Save the checkpoint with a category-specific name
    # We save both the timestamped version and a 'best' pointer
    dest_name = f"{CATEGORY_FILTER}_dice_{current_dice:.3f}.pth"
    dest_path = model_dir / dest_name
    shutil.copy(best_ckpt, dest_path)

    # Check if this is the all-time best for this category to update the inference pointer
    cat_best = df_report[df_report['category'] == CATEGORY_FILTER]['best_dice'].max()
    if current_dice >= cat_best:
        best_pointer = model_dir / f"best_{CATEGORY_FILTER}.pth"
        shutil.copy(best_ckpt, best_pointer)
        print(f'⭐ New best model for {CATEGORY_FILTER} saved to {best_pointer}')

    # 5. Save training log
    shutil.copy('/content/train.log', model_dir / f"{CATEGORY_FILTER}_train.log")
    print(f'✓ Checkpoint and log saved to Drive')

    display(df_report.tail(3))
else:
    print('USE_DRIVE=False or no checkpoint found — model not saved to Drive')

"""## 10. Full Map Inference using Best Model

This cell identifies the best model from the latest training run and applies it to segment buildings across a larger area.
"""

import os
import glob
import shutil
import requests
import subprocess
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from io import BytesIO
import time

# --- 1. CONFIGURATION ---
# Replace this with a specific Allmaps ID from your Supabase query
# (e.g., '1c80cda4-10cd-498c-850f-642de344165d')
ALLMAPS_ID = 'YOUR_ALLMAPS_ID_HERE'

TARGET_CATEGORY = CATEGORY_FILTER # From Step 1
TEMP_INFERENCE_DIR = '/content/temp_inference'

# Find the best model (Checking Drive first, then local logs)
drive_model_dir = os.path.join(DRIVE_CACHE, 'models')
best_model_path = os.path.join(drive_model_dir, f'best_{TARGET_CATEGORY}.pth')

if not os.path.exists(best_model_path):
    print(f"! Best model not found in Drive. Checking local logs...")
    local_logs = sorted(glob.glob(f'{MAPSAM2_DIR}/logs/vma_landplots*'), key=os.path.getmtime)
    if local_logs:
        ckpts = sorted(glob.glob(f'{local_logs[-1]}/Model/*.pth'))
        if ckpts:
            # Note: For production, we should map this to the max(dice_vals) index,
            # but we grab the latest available local checkpoint as a fallback.
            best_model_path = ckpts[-1]
            print(f"✓ Using local checkpoint: {best_model_path}")
        else:
            best_model_path = None
else:
    print(f"✓ Using best model from Drive: {best_model_path}")

if not best_model_path:
    raise RuntimeError(f"No checkpoint found for {TARGET_CATEGORY}. Please run training first.")


# --- 2. IIIF HELPER FUNCTIONS ---
def get_clean_iiif_base(allmaps_id):
    """Fetches the IIIF base URI and safely removes /info.json if present."""
    print(f"Resolving Allmaps ID: {allmaps_id}...")
    try:
        r = requests.get(f'https://annotations.allmaps.org/images/{allmaps_id}', timeout=15)
        if not r.ok:
            return None
        base = r.json().get('items', [{}])[0].get('target', {}).get('source', {}).get('id')
        if base:
            return base.replace('/info.json', '') # <-- Fix: Strip info.json to prevent 400 Bad Request
    except Exception as e:
        print(f"Error fetching IIIF base: {e}")
    return None

def get_iiif_tile(base_url, x, y, w, h, target_size=1024, max_retries=3):
    """Fetches a specific geographic crop from the IIIF server with retries."""
    base = base_url.rstrip('/')
    region = f"{x},{y},{w},{h}"
    size = f"{target_size},"

    tile_url = f"{base}/{region}/{size}/0/default.jpg"
    print(f"Fetching IIIF tile: {tile_url}")

    for attempt in range(max_retries):
        try:
            # Increased timeout to 120s for slow servers like Internet Archive
            r = requests.get(tile_url, timeout=120)
            r.raise_for_status()
            return Image.open(BytesIO(r.content)).convert('RGB')
        except requests.exceptions.Timeout:
            print(f"  [Attempt {attempt + 1}/{max_retries}] Timeout reached. Retrying in 5s...")
            time.sleep(5)
        except requests.exceptions.RequestException as e:
            print(f"  [Attempt {attempt + 1}/{max_retries}] Network error: {e}. Retrying in 5s...")
            time.sleep(5)
        except Exception as e:
            print(f"Failed to fetch tile: {e}")
            break # Break immediately on non-network/timeout errors (like image parsing failure)

    print("Failed to fetch tile after all retries.")
    return None


# --- 3. EXECUTE INFERENCE ---
if ALLMAPS_ID == 'YOUR_ALLMAPS_ID_HERE':
    # Fallback to the last processed map from Step 4 if the user forgot to set it
    if 'allmaps_id' in globals():
        ALLMAPS_ID = globals()['allmaps_id']
        print(f"Warning: ALLMAPS_ID not explicitly set. Falling back to the last map from loop: {ALLMAPS_ID}")
    else:
        raise ValueError("Please provide a valid ALLMAPS_ID to run inference.")

iiif_base = get_clean_iiif_base(ALLMAPS_ID)

if iiif_base:
    # We will test a 2048x2048 area starting at pixel coordinates 2048, 2048
    tx, ty, tw, th = 2048, 2048, 2048, 2048
    tile_img = get_iiif_tile(iiif_base, tx, ty, tw, th)

    if tile_img:
        print("\n--- Preparing MapSAM2 Inference Pipeline ---")

        # 1. Create a temporary "dummy dataset" structure for MapSAM2
        img_dir = os.path.join(TEMP_INFERENCE_DIR, 'test')
        ann_dir = os.path.join(TEMP_INFERENCE_DIR, 'annotation', 'test')
        os.makedirs(img_dir, exist_ok=True)
        os.makedirs(ann_dir, exist_ok=True)

        tile_filename = f"tile_{tx}_{ty}.png"
        img_path = os.path.join(img_dir, tile_filename)
        mask_path = os.path.join(ann_dir, tile_filename)

        # Save the real image
        tile_img.save(img_path)

        # Save a dummy ground truth mask (all black/0s) to satisfy the script
        dummy_mask = Image.new('L', tile_img.size, 0)
        dummy_mask.save(mask_path)

        # 2. Run MapSAM2 in Test Mode using the CLI
        os.chdir(MAPSAM2_DIR)
        CMD_TEST = (
            f"python train_2d.py -net sam2 -encoder {ENCODER} "
            f"-sam_ckpt {CKPT_PATH} -sam_config {SAM_CONFIG} "
            f"-data_path {TEMP_INFERENCE_DIR} -test_path {TEMP_INFERENCE_DIR} "
            f"-image_size 1024 -out_size 1024 -b 1 -rank {LORA_RANK} "
            f"-ft_ckpt {best_model_path} "
            f"-test -exp_name single_tile_inference"
        )
        print("Running prediction model (this may take a moment)...")

        # Capture output to catch any hidden errors instead of piping to tee
        result = subprocess.run(CMD_TEST, shell=True, capture_output=True, text=True)

        if result.returncode != 0:
            print(f"\n--- MapSAM2 Execution Failed (Return Code: {result.returncode}) ---")
            print(f"STDOUT:\n{result.stdout}")
            print(f"STDERR:\n{result.stderr}")
        else:
            # Save log for debugging just in case
            with open('/content/inference.log', 'w') as f:
                f.write(result.stdout)
                f.write(result.stderr)

            # 3. Locate the prediction output
            inference_log_dirs = sorted(glob.glob(f'{MAPSAM2_DIR}/logs/single_tile_inference*'), key=os.path.getmtime)

            if not inference_log_dirs:
                print("Error: MapSAM2 completed but no log directory was created.")
            else:
                inference_log_dir = inference_log_dirs[-1]
                pred_dir = os.path.join(inference_log_dir, 'Pred')

                # Use glob to find the file in case MapSAM2 appends a suffix
                stem = tile_filename.replace('.png', '')
                pred_candidates = glob.glob(os.path.join(pred_dir, f"*{stem}*.*"))

                # 4. Visualize the results
                if pred_candidates:
                    pred_path = pred_candidates[0]
                    pred_img = Image.open(pred_path).convert('L').resize(tile_img.size, Image.NEAREST)
                    pred_mask = np.array(pred_img) > 127

                    fig, axes = plt.subplots(1, 2, figsize=(14, 7))

                    # Show Original Tile
                    axes[0].imshow(tile_img)
                    axes[0].set_title(f'Original Tile ({tw}x{th} crop)')
                    axes[0].axis('off')

                    # Show Prediction Overlay
                    axes[1].imshow(tile_img)
                    overlay = np.zeros((*pred_mask.shape, 4), dtype=np.uint8)
                    overlay[pred_mask] = [255, 100, 0, 160] # Orange semi-transparent mask
                    axes[1].imshow(overlay)
                    axes[1].set_title(f'MapSAM2 Prediction: {TARGET_CATEGORY}')
                    axes[1].axis('off')

                    plt.tight_layout()
                    plt.show()

                    print(f"✓ Inference complete. Generated {(pred_mask).sum()} positive pixels.")

                    # Cleanup temp files
                    shutil.rmtree(TEMP_INFERENCE_DIR)

                else:
                    print(f"Error: Prediction file for {stem} was not generated by MapSAM2.")
                    print("Check /content/inference.log for clues.")

else:
    print("Could not resolve IIIF base. Check the Allmaps ID.")